<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 9 Conditional Probability | Solutions for Probability and Statistics for Scientists and Engineers</title>
<meta name="author" content="Matthew Davis">
<meta name="author" content="Brianna Hitt">
<meta name="author" content="Kenneth Horton">
<meta name="author" content="Bradley Warner">
<meta name="description" content="9.1 Objectives Define conditional probability and distinguish it from joint probability. Find a conditional probability using its definition. Using conditional probability, determine whether two...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 9 Conditional Probability | Solutions for Probability and Statistics for Scientists and Engineers">
<meta property="og:type" content="book">
<meta property="og:image" content="/figures/SolutionCoverPSSE.png">
<meta property="og:description" content="9.1 Objectives Define conditional probability and distinguish it from joint probability. Find a conditional probability using its definition. Using conditional probability, determine whether two...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 9 Conditional Probability | Solutions for Probability and Statistics for Scientists and Engineers">
<meta name="twitter:description" content="9.1 Objectives Define conditional probability and distinguish it from joint probability. Find a conditional probability using its definition. Using conditional probability, determine whether two...">
<meta name="twitter:image" content="/figures/SolutionCoverPSSE.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Solutions for Probability and Statistics for Scientists and Engineers</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li class="book-part">Descriptive Statistical Modeling</li>
<li><a class="" href="CS1.html"><span class="header-section-number">1</span> Case Study</a></li>
<li><a class="" href="DB.html"><span class="header-section-number">2</span> Data Basics</a></li>
<li><a class="" href="ODCP.html"><span class="header-section-number">3</span> Overview of Data Collection Principles</a></li>
<li><a class="" href="STUDY.html"><span class="header-section-number">4</span> Studies</a></li>
<li><a class="" href="NUMDATA.html"><span class="header-section-number">5</span> Numerical Data</a></li>
<li><a class="" href="CATDATA.html"><span class="header-section-number">6</span> Categorical Data</a></li>
<li class="book-part">Probability Modeling</li>
<li><a class="" href="CS2.html"><span class="header-section-number">7</span> Case Study</a></li>
<li><a class="" href="PROBRULES.html"><span class="header-section-number">8</span> Probability Rules</a></li>
<li><a class="active" href="CONDPROB.html"><span class="header-section-number">9</span> Conditional Probability</a></li>
<li><a class="" href="RANDVAR.html"><span class="header-section-number">10</span> Random Variables</a></li>
<li><a class="" href="CONRANDVAR.html"><span class="header-section-number">11</span> Continuous Random Variables</a></li>
<li><a class="" href="DISCRETENAMED.html"><span class="header-section-number">12</span> Named Discrete Distributions</a></li>
<li><a class="" href="CONTNNAMED.html"><span class="header-section-number">13</span> Named Continuous Distributions</a></li>
<li><a class="" href="MULTIDISTS.html"><span class="header-section-number">14</span> Multivariate Distributions</a></li>
<li><a class="" href="EST.html"><span class="header-section-number">15</span> Estimation Methods</a></li>
<li class="book-part">Statistical Modeling</li>
<li><a class="" href="CS3.html"><span class="header-section-number">16</span> Case Study</a></li>
<li><a class="" href="HYPOTEST.html"><span class="header-section-number">17</span> Hypothesis Testing</a></li>
<li><a class="" href="PVALUES.html"><span class="header-section-number">18</span> Empirical p-values</a></li>
<li><a class="" href="CLT.html"><span class="header-section-number">19</span> Central Limit Theorem</a></li>
<li><a class="" href="CI.html"><span class="header-section-number">20</span> Confidence Intervals</a></li>
<li><a class="" href="BOOT.html"><span class="header-section-number">21</span> Bootstrap</a></li>
<li><a class="" href="ADDTESTS.html"><span class="header-section-number">22</span> Additional Hypothesis Tests</a></li>
<li class="book-part">Predictive Statistical Modeling</li>
<li><a class="" href="CS4.html"><span class="header-section-number">23</span> Case Study</a></li>
<li><a class="" href="LRBASICS.html"><span class="header-section-number">24</span> Linear Regression Basics</a></li>
<li><a class="" href="LRINF.html"><span class="header-section-number">25</span> Linear Regression Inference</a></li>
<li><a class="" href="LRDIAG.html"><span class="header-section-number">26</span> Regression Diagnostics</a></li>
<li><a class="" href="LRSIM.html"><span class="header-section-number">27</span> Simulation Based Linear Regression</a></li>
<li><a class="" href="LRMULTI.html"><span class="header-section-number">28</span> Multiple Linear Regression</a></li>
<li><a class="" href="LOGREG.html"><span class="header-section-number">29</span> Logistic Regression</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="CONDPROB" class="section level1" number="9">
<h1>
<span class="header-section-number">9</span> Conditional Probability<a class="anchor" aria-label="anchor" href="#CONDPROB"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-8" class="section level2" number="9.1">
<h2>
<span class="header-section-number">9.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-8"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: decimal">
<li>Define conditional probability and distinguish it from joint probability.<br>
</li>
<li>Find a conditional probability using its definition.<br>
</li>
<li>Using conditional probability, determine whether two events are independent.<br>
</li>
<li>Apply Bayes’ Rule mathematically and via simulation.</li>
</ol>
</div>
<div id="homework-8" class="section level2" number="9.2">
<h2>
<span class="header-section-number">9.2</span> Homework<a class="anchor" aria-label="anchor" href="#homework-8"><i class="fas fa-link"></i></a>
</h2>
<div id="problem-1-8" class="section level3" number="9.2.1">
<h3>
<span class="header-section-number">9.2.1</span> Problem 1<a class="anchor" aria-label="anchor" href="#problem-1-8"><i class="fas fa-link"></i></a>
</h3>
<p>Consider Exercise 1 from Lesson 2. Recall: <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span> and <span class="math inline">\(C\)</span> are events such that <span class="math inline">\(\Prob(A)=0.5\)</span>, <span class="math inline">\(\Prob(B)=0.3\)</span>, <span class="math inline">\(\Prob(C)=0.4\)</span>, <span class="math inline">\(\Prob(A \cap B)=0.2\)</span>, <span class="math inline">\(\Prob(B \cap C)=0.12\)</span>, <span class="math inline">\(\Prob(A \cap C)=0.1\)</span>, and <span class="math inline">\(\Prob(A \cap B \cap C)=0.05\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>Are <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> independent?</li>
</ol>
<p>No. <span class="math inline">\(\Prob(A)\Prob(B)=0.15\neq \Prob(A\cap B)\)</span>.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Are <span class="math inline">\(B\)</span> and <span class="math inline">\(C\)</span> independent?</li>
</ol>
<p>Yes. <span class="math inline">\(\Prob(B)\Prob(C)=0.12 = \Prob(B\cap C)\)</span>. Also,
<span class="math display">\[
\Prob(B|C)=\frac{\Prob(B\cap C)}{\Prob(C)}= 0.12/0.4 = 0.3 =\Prob(B)
\]</span></p>
</div>
<div id="problem-2-8" class="section level3" number="9.2.2">
<h3>
<span class="header-section-number">9.2.2</span> Problem 2<a class="anchor" aria-label="anchor" href="#problem-2-8"><i class="fas fa-link"></i></a>
</h3>
<p>Suppose I have a biased coin (the probability I flip a heads is 0.6). I flip that coin twice. Assume that the coin is memoryless (flips are independent of one another).</p>
<ol style="list-style-type: lower-alpha">
<li>What is the probability that the second flip results in heads?</li>
</ol>
<p>0.6</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the probability that the second flip results in heads, given the first also resulted in heads?</li>
</ol>
<p>The coin is memoryless. So,
<span class="math display">\[
\Prob(\mbox{2nd flip heads}|\mbox{1st flip heads}) = 0.6
\]</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What is the probability both flips result in heads?</li>
</ol>
<p>Since the flips are independent,
<span class="math display">\[
\Prob(\mbox{both heads})=\Prob(\mbox{1st flip heads})\Prob(\mbox{2nd flip heads}) = 0.6*0.6=0.36
\]</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What is the probability exactly one coin flip results in heads?</li>
</ol>
<p>This could happen in two ways. The first could be heads OR the second could be heads.
<span class="math display">\[
\Prob(\mbox{exactly one heads})=\Prob(\mbox{1st flip heads})\Prob(\mbox{2nd flip tails}) + \Prob(\mbox{1st flip tails})\Prob(\mbox{2nd flip heads})
\]</span>
<span class="math display">\[
0.6*0.4+0.4*0.6 = 0.48
\]</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Now assume I flip the coin five times. What is the probability the result is 5 heads?
<span class="math display">\[
\Prob(\mbox{5 heads})= 0.6^5 = 0.0778
\]</span>
</li>
</ol>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">0.6</span><span class="op">^</span><span class="fl">5</span></code></pre></div>
<pre><code>## [1] 0.07776</code></pre>
<ol start="6" style="list-style-type: lower-alpha">
<li>What is the probability the result is exactly 2 heads (out of 5 flips)?</li>
</ol>
<p>There are <span class="math inline">\(\binom{5}{2} = 10\)</span> ways for this to happen ({HHTTT},{HTHTT},…). So,
<span class="math display">\[
\Prob(\mbox{2 heads out of 5 flips})=\binom{5}{2} 0.6^2(1-0.6)^3 = 0.2304
\]</span></p>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Special.html">choose</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">2</span><span class="op">)</span><span class="op">*</span><span class="fl">0.6</span><span class="op">^</span><span class="fl">2</span><span class="op">*</span><span class="fl">0.4</span><span class="op">^</span><span class="fl">3</span></code></pre></div>
<pre><code>## [1] 0.2304</code></pre>
</div>
<div id="problem-3-6" class="section level3" number="9.2.3">
<h3>
<span class="header-section-number">9.2.3</span> Problem 3<a class="anchor" aria-label="anchor" href="#problem-3-6"><i class="fas fa-link"></i></a>
</h3>
<p>(Adapted from IPSUR, <span class="citation">(<a href="references.html#ref-ipsur" role="doc-biblioref">Kerns 2010</a>)</span>). Suppose there are three assistants working at a company: Moe, Larry and Curly. All three assist with a filing process. Only one filing assistant is needed at a time. Moe assists 60% of the time, Larry assists 30% of the time and Curly assists the remaining 10% of the time. Occasionally, they make errors (misfiles); Moe has a misfile rate of 0.01, Larry has a misfile rate of 0.025, and Curly has a rate of 0.05. Suppose a misfile was discovered, but it is unknown who was on schedule when it occurred. Who is most likely to have committed the misfile? Calculate the probabilities for each of the three assistants.</p>
<p>Let <span class="math inline">\(E\)</span> be the event a misfile was committed. Also, let <span class="math inline">\(M\)</span>, <span class="math inline">\(L\)</span>, and <span class="math inline">\(C\)</span> denote the events that Moe, Larry and Curly was the assistant at the time, respectively.</p>
<p><span class="math display">\[
\Prob(E)=\Prob(E \cap M)+\Prob(E \cap L)+\Prob(E\cap C) 
\]</span>
<span class="math display">\[
= \Prob(E|M)\Prob(M)+\Prob(E|L)\Prob(L)+\Prob(E|C)\Prob(C) = 0.01*0.6+0.025*0.3+0.05*0.1 = 0.0185
\]</span></p>
<p>Thus,
<span class="math display">\[
\Prob(M|E)=\frac{\Prob(E \cap M)}{\Prob(E)}= \frac{0.01*0.6}{0.0185}=0.3243
\]</span></p>
<p>Similarly, <span class="math inline">\(\Prob(L|E)=0.4054\)</span> and <span class="math inline">\(\Prob(C|E)=0.2702\)</span>.</p>
<p>Larry is the assistant most likely to have committed the error.</p>
</div>
<div id="problem-4-2" class="section level3" number="9.2.4">
<h3>
<span class="header-section-number">9.2.4</span> Problem 4<a class="anchor" aria-label="anchor" href="#problem-4-2"><i class="fas fa-link"></i></a>
</h3>
<p>You are playing a game where there are two coins. One coin is fair and the other comes up <em>heads</em> 80% of the time. One coin is flipped 3 times and the result is three <em>heads</em>, what is the probability that the coin flipped is the fair coin? You will need to make an assumption about the probability of either coin being selected.</p>
<ol style="list-style-type: lower-alpha">
<li>Use Bayes formula to solve this problem.</li>
</ol>
<p>I will assume either coin is selected with a 50% probability.</p>
<p><span class="math display">\[
\Prob(Fair) = \Prob(Biased) = .5
\]</span>
<span class="math display">\[
\Prob(3 Heads|Fair)=\frac{1}{2}^3=\frac{1}{8}
\]</span>
<span class="math display">\[
\Prob(3 Heads|Biased)=.8^3=0.512
\]</span></p>
<p>Now</p>
<p><span class="math display">\[
\Prob(Fair | 3 Heads) = \frac{\Prob(3 Heads | Fair)\Prob(Fair)}{\Prob(3 Heads | Fair)\Prob(Fair)+\Prob(3 Heads| Biased)\Prob(Biased)}
\]</span></p>
<p>Which is</p>
<p><span class="math display">\[
\Prob(Fair | 3 Heads) =  \frac{\frac{1}{8}\frac{1}{2}}{\frac{1}{8}\frac{1}{2}+.8^{3}\frac{1}{2}} = 0.196
\]</span></p>
<div class="sourceCode" id="cb112"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">.125</span><span class="op">*</span><span class="fl">.5</span><span class="op">/</span><span class="op">(</span><span class="fl">.125</span><span class="op">*</span><span class="fl">.5</span><span class="op">+</span><span class="fl">.8</span><span class="op">^</span><span class="fl">3</span><span class="op">*</span><span class="fl">.5</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.1962323</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Use simulation to solve this problem.</li>
</ol>
<p>Let’s use the same assumptions. We could do this problem in two ways. We could flip each coin a fixed number of times and combine the information or use a random process to pick a flipped coin and then flip it three times. Let’s do the first.</p>
<p>Let’s flip a fair coin 50,000 times and count how many heads we get.</p>
<div class="sourceCode" id="cb114"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1154</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">50000</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/rflip.html">rflip</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">heads</span><span class="op">==</span><span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count<span class="op">=</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 6157</code></pre>
<p>Now flip the biased coin.</p>
<div class="sourceCode" id="cb116"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">50000</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/rflip.html">rflip</a></span><span class="op">(</span><span class="fl">3</span>,prob<span class="op">=</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">heads</span><span class="op">==</span><span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count<span class="op">=</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 25743</code></pre>
<p>So we have a total 6157 + 25743 heads of which 6157 came from the fair coin.</p>
<p>Thus the probability of the coin being fair given 3 heads on the flips is:</p>
<div class="sourceCode" id="cb118"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">6157</span><span class="op">/</span><span class="op">(</span><span class="fl">6157</span> <span class="op">+</span> <span class="fl">25743</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.1930094</code></pre>
<p>Or 19.3%.</p>
<p>Next pick a one of the coins with equal probability 100,000 times.</p>
<div class="sourceCode" id="cb120"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">501</span><span class="op">)</span>
<span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/rflip.html">rflip</a></span><span class="op">(</span><span class="fl">100000</span>,summarize <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">results</span></code></pre></div>
<pre><code>##       n heads tails prob
## 1 1e+05 50226 49774  0.5</code></pre>
<p>Now the fair coin was flipped 50226 times.</p>
<p>Let’s see how many times we get 3 heads when we flip that coin 3 times.</p>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">50226</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/rflip.html">rflip</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">heads</span><span class="op">==</span><span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count<span class="op">=</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 6270</code></pre>
<p>We have 6270 cases with 3 heads. Now for the biased coin.</p>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">49774</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/rflip.html">rflip</a></span><span class="op">(</span><span class="fl">3</span>,prob<span class="op">=</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">heads</span><span class="op">==</span><span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count<span class="op">=</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 25512</code></pre>
<p>Now we can determine the probability of a fair coin given 3 heads.</p>
<div class="sourceCode" id="cb126"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">6270</span><span class="op">/</span><span class="op">(</span><span class="fl">6270</span><span class="op">+</span><span class="fl">25512</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.1972815</code></pre>
<p>This code we could easily adapt if we don’t think each coin is being selected with the same frequency. Suppose we think the fair coin has a 75% chance of being selected. The analysis would look like this:</p>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">9021</span><span class="op">)</span>
<span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/rflip.html">rflip</a></span><span class="op">(</span><span class="fl">100000</span>,prob<span class="op">=</span><span class="fl">.75</span>,summarize <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">results</span></code></pre></div>
<pre><code>##       n heads tails prob
## 1 1e+05 75023 24977 0.75</code></pre>
<p>Now the fair coin was flipped 75023 times.</p>
<p>Let’s see how many times we get 3 heads when we flip that coin 3 times.</p>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">75023</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/rflip.html">rflip</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">heads</span><span class="op">==</span><span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count<span class="op">=</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 9579</code></pre>
<p>We have 9579 cases with 3 heads. Now for the biased coin.</p>
<div class="sourceCode" id="cb132"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">24977</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/rflip.html">rflip</a></span><span class="op">(</span><span class="fl">3</span>,prob<span class="op">=</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">heads</span><span class="op">==</span><span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count<span class="op">=</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 12789</code></pre>
<p>Now we can determine the probability of a fair coin given 3 heads.</p>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">9579</span><span class="op">/</span><span class="op">(</span><span class="fl">9579</span><span class="op">+</span><span class="fl">12789</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.4282457</code></pre>
<p>A much different answer. That is because prior to getting the data we believed the fair coin would be selected with a 75% probability. The data indicates that we need to update and lower this probability. We only flipped 3 times but the evidence is so in favor of the biased coin, that our probability dropped substantially. This is why Bayes is such a powerful tool.</p>
<p>Think about what we just did with this problem. We started with a subjective believe that either coin would be selected with equal probability. This is called the prior probability. We then collected data on three flips of the coin. We used this empirical data to update our belief into a posterior probability. This is the basis for Bayesian statistical analysis. Bayesian statistics is an entire discipline unto itself.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="PROBRULES.html"><span class="header-section-number">8</span> Probability Rules</a></div>
<div class="next"><a href="RANDVAR.html"><span class="header-section-number">10</span> Random Variables</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#CONDPROB"><span class="header-section-number">9</span> Conditional Probability</a></li>
<li><a class="nav-link" href="#objectives-8"><span class="header-section-number">9.1</span> Objectives</a></li>
<li>
<a class="nav-link" href="#homework-8"><span class="header-section-number">9.2</span> Homework</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#problem-1-8"><span class="header-section-number">9.2.1</span> Problem 1</a></li>
<li><a class="nav-link" href="#problem-2-8"><span class="header-section-number">9.2.2</span> Problem 2</a></li>
<li><a class="nav-link" href="#problem-3-6"><span class="header-section-number">9.2.3</span> Problem 3</a></li>
<li><a class="nav-link" href="#problem-4-2"><span class="header-section-number">9.2.4</span> Problem 4</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Solutions for Probability and Statistics for Scientists and Engineers</strong>" was written by Matthew Davis, Brianna Hitt, Kenneth Horton, Bradley Warner. It was last built on 2022-01-03.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
