<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 16 Case Study | Solutions for Probability and Statistics for Scientists and Engineers</title>
<meta name="author" content="Matthew Davis">
<meta name="author" content="Brianna Hitt">
<meta name="author" content="Kenneth Horton">
<meta name="author" content="Bradley Warner">
<meta name="description" content="16.1 Objectives Define and use properly in context all new terminology. Conduct a hypothesis test using a permutation test to include all 4 steps.  16.2 Homework  16.2.1 Problem 1 Side effects of...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 16 Case Study | Solutions for Probability and Statistics for Scientists and Engineers">
<meta property="og:type" content="book">
<meta property="og:image" content="/figures/SolutionCoverPSSE.png">
<meta property="og:description" content="16.1 Objectives Define and use properly in context all new terminology. Conduct a hypothesis test using a permutation test to include all 4 steps.  16.2 Homework  16.2.1 Problem 1 Side effects of...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 16 Case Study | Solutions for Probability and Statistics for Scientists and Engineers">
<meta name="twitter:description" content="16.1 Objectives Define and use properly in context all new terminology. Conduct a hypothesis test using a permutation test to include all 4 steps.  16.2 Homework  16.2.1 Problem 1 Side effects of...">
<meta name="twitter:image" content="/figures/SolutionCoverPSSE.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Solutions for Probability and Statistics for Scientists and Engineers</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li class="book-part">Descriptive Statistical Modeling</li>
<li><a class="" href="CS1.html"><span class="header-section-number">1</span> Case Study</a></li>
<li><a class="" href="DB.html"><span class="header-section-number">2</span> Data Basics</a></li>
<li><a class="" href="ODCP.html"><span class="header-section-number">3</span> Overview of Data Collection Principles</a></li>
<li><a class="" href="STUDY.html"><span class="header-section-number">4</span> Studies</a></li>
<li><a class="" href="NUMDATA.html"><span class="header-section-number">5</span> Numerical Data</a></li>
<li><a class="" href="CATDATA.html"><span class="header-section-number">6</span> Categorical Data</a></li>
<li class="book-part">Probability Modeling</li>
<li><a class="" href="CS2.html"><span class="header-section-number">7</span> Case Study</a></li>
<li><a class="" href="PROBRULES.html"><span class="header-section-number">8</span> Probability Rules</a></li>
<li><a class="" href="CONDPROB.html"><span class="header-section-number">9</span> Conditional Probability</a></li>
<li><a class="" href="RANDVAR.html"><span class="header-section-number">10</span> Random Variables</a></li>
<li><a class="" href="CONRANDVAR.html"><span class="header-section-number">11</span> Continuous Random Variables</a></li>
<li><a class="" href="DISCRETENAMED.html"><span class="header-section-number">12</span> Named Discrete Distributions</a></li>
<li><a class="" href="CONTNNAMED.html"><span class="header-section-number">13</span> Named Continuous Distributions</a></li>
<li><a class="" href="MULTIDISTS.html"><span class="header-section-number">14</span> Multivariate Distributions</a></li>
<li><a class="" href="EST.html"><span class="header-section-number">15</span> Estimation Methods</a></li>
<li class="book-part">Statistical Modeling</li>
<li><a class="active" href="CS3.html"><span class="header-section-number">16</span> Case Study</a></li>
<li><a class="" href="HYPOTEST.html"><span class="header-section-number">17</span> Hypothesis Testing</a></li>
<li><a class="" href="PVALUES.html"><span class="header-section-number">18</span> Empirical p-values</a></li>
<li><a class="" href="CLT.html"><span class="header-section-number">19</span> Central Limit Theorem</a></li>
<li><a class="" href="CI.html"><span class="header-section-number">20</span> Confidence Intervals</a></li>
<li><a class="" href="BOOT.html"><span class="header-section-number">21</span> Bootstrap</a></li>
<li><a class="" href="ADDTESTS.html"><span class="header-section-number">22</span> Additional Hypothesis Tests</a></li>
<li class="book-part">Predictive Statistical Modeling</li>
<li><a class="" href="CS4.html"><span class="header-section-number">23</span> Case Study</a></li>
<li><a class="" href="LRBASICS.html"><span class="header-section-number">24</span> Linear Regression Basics</a></li>
<li><a class="" href="LRINF.html"><span class="header-section-number">25</span> Linear Regression Inference</a></li>
<li><a class="" href="LRDIAG.html"><span class="header-section-number">26</span> Regression Diagnostics</a></li>
<li><a class="" href="LRSIM.html"><span class="header-section-number">27</span> Simulation Based Linear Regression</a></li>
<li><a class="" href="LRMULTI.html"><span class="header-section-number">28</span> Multiple Linear Regression</a></li>
<li><a class="" href="LOGREG.html"><span class="header-section-number">29</span> Logistic Regression</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="CS3" class="section level1" number="16">
<h1>
<span class="header-section-number">16</span> Case Study<a class="anchor" aria-label="anchor" href="#CS3"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-15" class="section level2" number="16.1">
<h2>
<span class="header-section-number">16.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-15"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: decimal">
<li>Define and use properly in context all new terminology.<br>
</li>
<li>Conduct a hypothesis test using a permutation test to include all 4 steps.</li>
</ol>
</div>
<div id="homework-15" class="section level2" number="16.2">
<h2>
<span class="header-section-number">16.2</span> Homework<a class="anchor" aria-label="anchor" href="#homework-15"><i class="fas fa-link"></i></a>
</h2>
<div id="problem-1-15" class="section level3" number="16.2.1">
<h3>
<span class="header-section-number">16.2.1</span> Problem 1<a class="anchor" aria-label="anchor" href="#problem-1-15"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Side effects of Avandia</strong></p>
<p>Rosiglitazone is the active ingredient in the controversial type~2 diabetes medicine Avandia and has been linked to an increased risk of serious cardiovascular problems such as stroke, heart failure, and death. A common alternative treatment is pioglitazone, the active ingredient in a diabetes medicine called Actos. In a nationwide retrospective observational study of 227,571 Medicare beneficiaries aged 65 years or older, it was found that 2,593 of the 67,593 patients using rosiglitazone and 5,386 of the 159,978 using pioglitazone had serious cardiovascular problems. These data are summarized in the contingency table below.</p>
<p><span class="math display">\[
\begin{array}{ccc|cc|c} &amp; &amp; &amp;\textbf{Cardiovascular} &amp; \textbf{problems} &amp;
\\&amp; &amp;       &amp; Yes   &amp; No        &amp; Total \\
&amp;\hline \textbf{Treatment}      &amp; \textit{Rosiglitazone}    &amp; 2,593 &amp; 65,000        &amp; 67,593    \\
&amp; &amp; \textit{Pioglitazone}       &amp; 5,386     &amp; 154,592   &amp; 159,978\\
&amp;\hline &amp;Total          &amp; 7,979 &amp; 219,592       &amp; 227,571
\end{array} 
\]</span></p>
<p>Determine if each of the following statements is true or false. If false, explain why.  The reasoning may be wrong even if the statement’s conclusion is correct. In such cases, the statement should be considered false.</p>
<ol style="list-style-type: lower-alpha">
<li>Since more patients on pioglitazone had cardiovascular problems (5,386 vs. 2,593), we can conclude that the rate of cardiovascular problems for those on a pioglitazone treatment is higher.</li>
</ol>
<p>False. Instead of comparing counts, we should compare percentages.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>The data suggest that diabetic patients who are taking rosiglitazone are more likely to have cardiovascular problems since the rate of incidence was (2,593 / 67,593 = 0.038) 3.8% for patients on this treatment, while it was only (5,386 / 159,978 = 0.034) 3.4% for patients on pioglitazone.</li>
</ol>
<p>True.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>The fact that the rate of incidence is higher for the rosiglitazone group proves that rosiglitazone causes serious cardiovascular problems.</li>
</ol>
<p>False. We cannot infer a causal relationship from an association in an observational study. However, we can say the drug a person is on affects his risk in this case, as he chose that drug and his choice may be associated with other variables, which is why part (b) is true. The difference in these statements is subtle but important.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Based on the information provided so far, we cannot tell if the difference between the rates of incidences is due to a relationship between the two variables or due to chance.</li>
</ol>
<p>True.</p>
<div style="page-break-after: always;"></div>
</div>
<div id="problem-2-15" class="section level3" number="16.2.2">
<h3>
<span class="header-section-number">16.2.2</span> Problem 2<a class="anchor" aria-label="anchor" href="#problem-2-15"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Heart transplants</strong></p>
<p>The Stanford University Heart Transplant Study was conducted to determine whether an experimental heart transplant program increased lifespan. Each patient entering the program was designated an official heart transplant candidate, meaning that he was gravely ill and would most likely benefit from a new heart. Some patients got a transplant and some did not. The variable  indicates which group the patients were in; patients in the treatment group got a transplant and those in the control group did not. Another variable called  was used to indicate whether or not the patient was alive at the end of the study.</p>
<p>In the study, of the 34 patients in the control group, 4 were alive at the end of the study. Of the 69 patients in the treatment group, 24 were alive. The contingency table below summarizes these results.</p>
<p><span class="math display">\[
\begin{array}{ccc|cc|c} &amp; &amp; &amp;\textbf{Group} &amp;  &amp;
\\&amp; &amp;       &amp; Control   &amp; Treatment         &amp; Total \\
&amp;\hline \textbf{Outcome}        &amp; \textit{Alive}    &amp; 4     &amp; 24            &amp; 28    \\
&amp; &amp; \textit{Dead}       &amp; 30        &amp; 45            &amp; 75\\
&amp;\hline &amp;Total              &amp; 34        &amp; 69            &amp; 103
\end{array} 
\]</span></p>
<p>The data is in a file called <strong>Stanford_heart_study.csv</strong>. Read the data in and answer the following questions.</p>
<div class="sourceCode" id="cb308"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">heart</span><span class="op">&lt;-</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/Stanford_heart_study.csv"</span><span class="op">)</span></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li>What proportion of patients in the treatment group and what proportion of patients in the control group died?</li>
</ol>
<div class="sourceCode" id="cb309"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaicCore/man/inspect.html">inspect</a></span><span class="op">(</span><span class="va">heart</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## categorical variables:  
##      name     class levels   n missing
## 1 outcome character      2 103       0
## 2   group character      2 103       0
##                                    distribution
## 1 Dead (72.8%), Alive (27.2%)                  
## 2 Treatment (67%), Control (33%)</code></pre>
<div class="sourceCode" id="cb311"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaicCore/man/tally.html">tally</a></span><span class="op">(</span><span class="op">~</span><span class="va">outcome</span><span class="op">+</span><span class="va">group</span>,data<span class="op">=</span><span class="va">heart</span>,margins <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>##        group
## outcome Control Treatment Total
##   Alive       4        24    28
##   Dead       30        45    75
##   Total      34        69   103</code></pre>
<div class="sourceCode" id="cb313"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaicCore/man/tally.html">tally</a></span><span class="op">(</span><span class="va">outcome</span><span class="op">~</span><span class="va">group</span>,data<span class="op">=</span><span class="va">heart</span>,margins <span class="op">=</span> <span class="cn">TRUE</span>,format<span class="op">=</span><span class="st">"percent"</span><span class="op">)</span></code></pre></div>
<pre><code>##        group
## outcome   Control Treatment
##   Alive  11.76471  34.78261
##   Dead   88.23529  65.21739
##   Total 100.00000 100.00000</code></pre>
<p>So 88.2% of patients in control group died and 65.2% in the treatment group.</p>
<p>One approach for investigating whether or not the treatment is effective is to use a randomization technique.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What are the claims being tested? Use the same null and alternative hypothesis notation used in the lesson notes.</li>
</ol>
<p><span class="math inline">\(H_0\)</span>: <strong>Independence model</strong>. The variables <em>group</em> and <em>outcome</em> are independent. They have no relationship, and the difference in survival rates between the control and treatment groups was due to chance. In other words, heart transplant is not effective.<br><span class="math inline">\(H_A\)</span>: <strong>Alternative hypothesis</strong>. The variables <em>group</em> and <em>outcome</em> are <strong>not</strong> independent. The difference in survival rates between the control and treatment groups was not due
to chance and the heart transplant is effective.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>The paragraph below describes the set up for such approach, if we were to do it without using statistical software. Fill in the blanks with a number or phrase, whichever is appropriate.</li>
</ol>
<p>We write <em>alive</em> on <strong>28</strong> cards representing patients who were alive at the end of the study, and <em>dead</em> on <strong>75</strong> cards representing patients who were not. Then, we shuffle these cards and split them into two groups: one group of size <strong>69</strong> representing treatment, and another group of size <strong>34</strong> representing control. We calculate the difference between the proportion of <em>dead</em> cards in the control and treatment groups (control - treatment), this is just so we have positive observed value, and record this value. We repeat this many times to build a distribution centered at <strong>zero</strong>. Lastly, we calculate the fraction of simulations where the simulated differences in proportions are <strong>0.23</strong> or <strong>greater</strong>. If this fraction of simulations, the empirical p-value, is low, we conclude that it is unlikely to have observed such an outcome by chance and that the null hypothesis should be rejected in favor of the alternative.</p>
<p>Next we will perform the simulation and use results to decide the effectiveness of the transplant program.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Find observed value of the test statistic, which we decided to use the difference in proportions.</li>
</ol>
<div class="sourceCode" id="cb315"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">obs</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/diffmean.html">diffprop</a></span><span class="op">(</span><span class="va">outcome</span><span class="op">~</span><span class="va">group</span>,data<span class="op">=</span><span class="va">heart</span><span class="op">)</span>
<span class="va">obs</span></code></pre></div>
<pre><code>## diffprop 
## 0.230179</code></pre>
<ol start="5" style="list-style-type: lower-alpha">
<li>Simulate 1000 values of the test statistic by using <code><a href="https://rdrr.io/pkg/mosaic/man/resample.html">shuffle()</a></code> on the variable <code>group</code>.</li>
</ol>
<div class="sourceCode" id="cb317"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1213</span><span class="op">)</span>
<span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">1000</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/diffmean.html">diffprop</a></span><span class="op">(</span><span class="va">outcome</span><span class="op">~</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/resample.html">shuffle</a></span><span class="op">(</span><span class="va">group</span><span class="op">)</span>,data<span class="op">=</span><span class="va">heart</span><span class="op">)</span></code></pre></div>
<ol start="6" style="list-style-type: lower-alpha">
<li>Plot distribution of results. Include a vertical line for the observed value. Clean up the plot as if you were presenting to a decision maker.</li>
</ol>
<div class="sourceCode" id="cb318"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">results</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_histogram</span><span class="op">(</span><span class="op">~</span><span class="va">diffprop</span>,xlab<span class="op">=</span><span class="st">"Difference in proportions"</span>,
               ylab<span class="op">=</span><span class="st">"Count"</span>,
               fill<span class="op">=</span><span class="st">"cyan"</span>,
               color<span class="op">=</span><span class="st">"black"</span>,
               title<span class="op">=</span><span class="st">"Stanford Heart Study"</span>,
               subtitle<span class="op">=</span><span class="st">"Distribution of difference between control and treatment groups"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_vline</span><span class="op">(</span>xintercept <span class="op">=</span><span class="va">obs</span> <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_theme</span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="18-Hypothesis-Testing-Case-Study-Solutions_files/figure-html/unnamed-chunk-8-1.png" width="672"></div>
<ol start="7" style="list-style-type: lower-alpha">
<li>Find p-value. Think carefully about what more extreme would mean.</li>
</ol>
<div class="sourceCode" id="cb319"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">results</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>p_value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">mean</a></span><span class="op">(</span><span class="va">diffprop</span><span class="op">&gt;=</span><span class="va">obs</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##   p_value
## 1   0.011</code></pre>
<p>If we wanted to use a <code>hypergeometric</code>. We could use any of the cell in the table. We will use the upper left. More extreme would be 4 or fewer in the control group being alive. We get a similar p-value.</p>
<div class="sourceCode" id="cb321"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaicCore/man/tally.html">tally</a></span><span class="op">(</span><span class="op">~</span><span class="va">outcome</span><span class="op">+</span><span class="va">group</span>,data<span class="op">=</span><span class="va">heart</span>,margins <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>##        group
## outcome Control Treatment Total
##   Alive       4        24    28
##   Dead       30        45    75
##   Total      34        69   103</code></pre>
<div class="sourceCode" id="cb323"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/Hypergeometric.html">phyper</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">34</span>,<span class="fl">69</span>,<span class="fl">28</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.01039537</code></pre>
<ol start="8" style="list-style-type: lower-alpha">
<li>Decide if the treatment is effective.</li>
</ol>
<p>Under the independence model, only 11 out of 1000 times (1.1%) did we get a difference of 0.23 or higher between the proportions of patients that died in the control and treatment groups. Since this is a low probability, we can reject the claim of independence in favor of the alternate model. There is convincing evidence to suggest that the transplant program is effective.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="EST.html"><span class="header-section-number">15</span> Estimation Methods</a></div>
<div class="next"><a href="HYPOTEST.html"><span class="header-section-number">17</span> Hypothesis Testing</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#CS3"><span class="header-section-number">16</span> Case Study</a></li>
<li><a class="nav-link" href="#objectives-15"><span class="header-section-number">16.1</span> Objectives</a></li>
<li>
<a class="nav-link" href="#homework-15"><span class="header-section-number">16.2</span> Homework</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#problem-1-15"><span class="header-section-number">16.2.1</span> Problem 1</a></li>
<li><a class="nav-link" href="#problem-2-15"><span class="header-section-number">16.2.2</span> Problem 2</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Solutions for Probability and Statistics for Scientists and Engineers</strong>" was written by Matthew Davis, Brianna Hitt, Kenneth Horton, Bradley Warner. It was last built on 2022-02-01.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
