<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 24 Linear Regression Basics | Solutions for Probability and Statistics for Scientists and Engineers</title>
<meta name="author" content="Matthew Davis">
<meta name="author" content="Brianna Hitt">
<meta name="author" content="Kenneth Horton">
<meta name="author" content="Bradley Warner">
<meta name="description" content="24.1 Objectives Obtain parameter estimates of a simple linear regression model given a sample of data. Interpret the coefficients of a simple linear regression. Create a scatterplot with a...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 24 Linear Regression Basics | Solutions for Probability and Statistics for Scientists and Engineers">
<meta property="og:type" content="book">
<meta property="og:image" content="/figures/SolutionCoverPSSE.png">
<meta property="og:description" content="24.1 Objectives Obtain parameter estimates of a simple linear regression model given a sample of data. Interpret the coefficients of a simple linear regression. Create a scatterplot with a...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 24 Linear Regression Basics | Solutions for Probability and Statistics for Scientists and Engineers">
<meta name="twitter:description" content="24.1 Objectives Obtain parameter estimates of a simple linear regression model given a sample of data. Interpret the coefficients of a simple linear regression. Create a scatterplot with a...">
<meta name="twitter:image" content="/figures/SolutionCoverPSSE.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Solutions for Probability and Statistics for Scientists and Engineers</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li class="book-part">Descriptive Statistical Modeling</li>
<li><a class="" href="CS1.html"><span class="header-section-number">1</span> Case Study</a></li>
<li><a class="" href="DB.html"><span class="header-section-number">2</span> Data Basics</a></li>
<li><a class="" href="ODCP.html"><span class="header-section-number">3</span> Overview of Data Collection Principles</a></li>
<li><a class="" href="STUDY.html"><span class="header-section-number">4</span> Studies</a></li>
<li><a class="" href="NUMDATA.html"><span class="header-section-number">5</span> Numerical Data</a></li>
<li><a class="" href="CATDATA.html"><span class="header-section-number">6</span> Categorical Data</a></li>
<li class="book-part">Probability Modeling</li>
<li><a class="" href="CS2.html"><span class="header-section-number">7</span> Case Study</a></li>
<li><a class="" href="PROBRULES.html"><span class="header-section-number">8</span> Probability Rules</a></li>
<li><a class="" href="CONDPROB.html"><span class="header-section-number">9</span> Conditional Probability</a></li>
<li><a class="" href="RANDVAR.html"><span class="header-section-number">10</span> Random Variables</a></li>
<li><a class="" href="CONRANDVAR.html"><span class="header-section-number">11</span> Continuous Random Variables</a></li>
<li><a class="" href="DISCRETENAMED.html"><span class="header-section-number">12</span> Named Discrete Distributions</a></li>
<li><a class="" href="CONTNNAMED.html"><span class="header-section-number">13</span> Named Continuous Distributions</a></li>
<li><a class="" href="MULTIDISTS.html"><span class="header-section-number">14</span> Multivariate Distributions</a></li>
<li><a class="" href="EST.html"><span class="header-section-number">15</span> Estimation Methods</a></li>
<li class="book-part">Statistical Modeling</li>
<li><a class="" href="CS3.html"><span class="header-section-number">16</span> Case Study</a></li>
<li><a class="" href="HYPOTEST.html"><span class="header-section-number">17</span> Hypothesis Testing</a></li>
<li><a class="" href="PVALUES.html"><span class="header-section-number">18</span> Empirical p-values</a></li>
<li><a class="" href="CLT.html"><span class="header-section-number">19</span> Central Limit Theorem</a></li>
<li><a class="" href="CI.html"><span class="header-section-number">20</span> Confidence Intervals</a></li>
<li><a class="" href="BOOT.html"><span class="header-section-number">21</span> Bootstrap</a></li>
<li><a class="" href="ADDTESTS.html"><span class="header-section-number">22</span> Additional Hypothesis Tests</a></li>
<li class="book-part">Predictive Statistical Modeling</li>
<li><a class="" href="CS4.html"><span class="header-section-number">23</span> Case Study</a></li>
<li><a class="active" href="LRBASICS.html"><span class="header-section-number">24</span> Linear Regression Basics</a></li>
<li><a class="" href="LRINF.html"><span class="header-section-number">25</span> Linear Regression Inference</a></li>
<li><a class="" href="LRDIAG.html"><span class="header-section-number">26</span> Regression Diagnostics</a></li>
<li><a class="" href="LRSIM.html"><span class="header-section-number">27</span> Simulation Based Linear Regression</a></li>
<li><a class="" href="LRMULTI.html"><span class="header-section-number">28</span> Multiple Linear Regression</a></li>
<li><a class="" href="LOGREG.html"><span class="header-section-number">29</span> Logistic Regression</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="LRBASICS" class="section level1" number="24">
<h1>
<span class="header-section-number">24</span> Linear Regression Basics<a class="anchor" aria-label="anchor" href="#LRBASICS"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-22" class="section level2" number="24.1">
<h2>
<span class="header-section-number">24.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-22"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: decimal">
<li>Obtain parameter estimates of a simple linear regression model given a sample of data.<br>
</li>
<li>Interpret the coefficients of a simple linear regression.<br>
</li>
<li>Create a scatterplot with a regression line.<br>
</li>
<li>Explain and check the assumptions of linear regression.<br>
</li>
<li>Use and be able to explain all new terms.</li>
</ol>
</div>
<div id="homework-23" class="section level2" number="24.2">
<h2>
<span class="header-section-number">24.2</span> Homework<a class="anchor" aria-label="anchor" href="#homework-23"><i class="fas fa-link"></i></a>
</h2>
<div id="problem-1-23" class="section level3" number="24.2.1">
<h3>
<span class="header-section-number">24.2.1</span> Problem 1<a class="anchor" aria-label="anchor" href="#problem-1-23"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Nutrition at Starbucks</strong></p>
<p>In the <code>data</code> folder is a file named <code>starbucks.csv</code>. Use it to answer the questions below.</p>
<ol style="list-style-type: lower-alpha">
<li>Create a scatterplot of number of calories and amount of carbohydrates.</li>
</ol>
<div class="sourceCode" id="cb580"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starbucks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/starbucks.csv"</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 77 Columns: 7</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: ","
## chr (2): item, type
## dbl (5): calories, fat, carb, fiber, protein</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb584"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">starbucks</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 77
## Columns: 7
## $ item     &lt;chr&gt; "8-Grain Roll", "Apple Bran Muffin", "Apple Fritter", "Banana…
## $ calories &lt;dbl&gt; 350, 350, 420, 490, 130, 370, 460, 370, 310, 420, 380, 320, 3…
## $ fat      &lt;dbl&gt; 8, 9, 20, 19, 6, 14, 22, 14, 18, 25, 17, 12, 17, 21, 5, 18, 1…
## $ carb     &lt;dbl&gt; 67, 64, 59, 75, 17, 47, 61, 55, 32, 39, 51, 53, 34, 57, 52, 7…
## $ fiber    &lt;dbl&gt; 5, 7, 0, 4, 0, 5, 2, 0, 0, 0, 2, 3, 2, 2, 3, 3, 2, 3, 0, 2, 0…
## $ protein  &lt;dbl&gt; 10, 6, 5, 7, 0, 6, 7, 6, 5, 7, 4, 6, 5, 5, 12, 7, 8, 6, 0, 10…
## $ type     &lt;chr&gt; "bakery", "bakery", "bakery", "bakery", "bakery", "bakery", "…</code></pre>
<div class="sourceCode" id="cb586"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starbucks</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_point</span><span class="op">(</span><span class="va">calories</span><span class="op">~</span><span class="va">carb</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_labs</span><span class="op">(</span>x<span class="op">=</span><span class="st">"Carbohydrate Content (g)"</span>,y<span class="op">=</span><span class="st">"Calories"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_theme</span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="26-Linear-Regression-Basics-Solutions_files/figure-html/unnamed-chunk-3-1.png" width="672"></div>
<p>We put <code>calories</code> as the response.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Describe the relationship in the graph.</li>
</ol>
<p>There is a positive, moderate, linear association between number of calories and amount of carbohydrates. In addition, the amount of carbohydrates is more variable for menu items with higher calories, indicating non-constant variance. There also appear to be two clusters of data: a patch of about a dozen observations in the lower left and a
larger patch on the right side. There might be some natural groupings of the these points. For example, the points in the lower left might come from a <em>light</em> menu.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>In this scenario, what are the explanatory and response variables?</li>
</ol>
<p>Response: number of calories. Explanatory: amount of carbohydrates (in grams).</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Why might we want to fit a regression line to these data?</li>
</ol>
<p>With a regression line, we can predict the amount of calories for a given number of carbohydrates. This may be useful if you are concerned about your carb intake and its impact on calorie consumption. Typically you can get both on the menu so this model might not be that valuable.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Create a scatterplot of number of calories and amount of carbohydrates with the regression line included.</li>
</ol>
<div class="sourceCode" id="cb587"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starbucks</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_point</span><span class="op">(</span><span class="va">calories</span><span class="op">~</span><span class="va">carb</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_labs</span><span class="op">(</span>x<span class="op">=</span><span class="st">"Carbohydrate Content (g)"</span>,y<span class="op">=</span><span class="st">"Calories"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_lm</span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_theme</span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="26-Linear-Regression-Basics-Solutions_files/figure-html/unnamed-chunk-4-1.png" width="672"></div>
<ol start="6" style="list-style-type: lower-alpha">
<li>Using ’lm()` fit a least squares line to the data.</li>
</ol>
<div class="sourceCode" id="cb588"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">star_mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">calories</span><span class="op">~</span><span class="va">carb</span>,data<span class="op">=</span><span class="va">starbucks</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb589"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">star_mod</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = calories ~ carb, data = starbucks)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -151.962  -70.556   -0.636   54.908  179.444 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 146.0204    25.9186   5.634 2.93e-07 ***
## carb          4.2971     0.5424   7.923 1.67e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 78.26 on 75 degrees of freedom
## Multiple R-squared:  0.4556, Adjusted R-squared:  0.4484 
## F-statistic: 62.77 on 1 and 75 DF,  p-value: 1.673e-11</code></pre>
<ol start="7" style="list-style-type: lower-alpha">
<li>Report and interpret the slope coefficient.</li>
</ol>
<p>The estimated slope is 4.297 so one additional gram of carbohydrates results in an average increase in calories of 4.297.</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>For a menu item with 51 g of carbs, what is the estimated calorie count?</li>
</ol>
<div class="sourceCode" id="cb591"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">146.0204</span><span class="op">+</span><span class="fl">4.2971</span><span class="op">*</span><span class="fl">51</span></code></pre></div>
<pre><code>## [1] 365.1725</code></pre>
<ol style="list-style-type: lower-roman">
<li>Could we use the model for a menu item with 100 g of carbs?</li>
</ol>
<div class="sourceCode" id="cb593"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">starbucks</span><span class="op">)</span></code></pre></div>
<pre><code>##      item              calories          fat             carb      
##  Length:77          Min.   : 80.0   Min.   : 0.00   Min.   :16.00  
##  Class :character   1st Qu.:300.0   1st Qu.: 9.00   1st Qu.:31.00  
##  Mode  :character   Median :350.0   Median :13.00   Median :45.00  
##                     Mean   :338.8   Mean   :13.77   Mean   :44.87  
##                     3rd Qu.:420.0   3rd Qu.:18.00   3rd Qu.:59.00  
##                     Max.   :500.0   Max.   :28.00   Max.   :80.00  
##      fiber          protein           type          
##  Min.   :0.000   Min.   : 0.000   Length:77         
##  1st Qu.:0.000   1st Qu.: 5.000   Class :character  
##  Median :2.000   Median : 7.000   Mode  :character  
##  Mean   :2.221   Mean   : 9.481                     
##  3rd Qu.:4.000   3rd Qu.:15.000                     
##  Max.   :7.000   Max.   :34.000</code></pre>
<p>The maximum carb value is 80 so 100 is outside of the observed data. It would be suspect to extrapolate to that value.</p>
<ol start="10" style="list-style-type: lower-alpha">
<li>Does the assumption of constant variance seem reasonable for this problem?</li>
</ol>
<p>We are going to use the <code>broom</code> package to get the residuals and corresponding independent variable values. You could also get the residuals from the model object and the independent variable values from the original dataframe.</p>
<div class="sourceCode" id="cb595"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb596"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">star_mod</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_point</span><span class="op">(</span><span class="va">.resid</span><span class="op">~</span><span class="va">carb</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_theme</span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_labs</span><span class="op">(</span>title<span class="op">=</span><span class="st">"Residual plot"</span>,x<span class="op">=</span><span class="st">"Carbohydrates"</span>,y<span class="op">=</span><span class="st">"Residual"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="26-Linear-Regression-Basics-Solutions_files/figure-html/unnamed-chunk-10-1.png" width="672"></div>
<p>It seems that the variance in the second group is larger that the first, so it may not be a reasonable assumption. Also note that the linearity assumption is also questionable.</p>
<ol start="11" style="list-style-type: lower-alpha">
<li>Verify that the line passes through the mean carb and mean calories, do this mathematically.</li>
</ol>
<div class="sourceCode" id="cb597"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">146.0204</span><span class="op">+</span><span class="fl">4.2971</span><span class="op">*</span><span class="fl">44.87</span></code></pre></div>
<pre><code>## [1] 338.8313</code></pre>
<p>It checks.</p>
<ol start="12" style="list-style-type: lower-alpha">
<li>What is the estimate of the standard deviation of the residuals? How could you use this information?</li>
</ol>
<p>The estimate is 78.26. If the normal assumption is accurate, we would expect a majority of observations to be within <span class="math inline">\(\pm\)</span> 78.26 calories of the line.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="CS4.html"><span class="header-section-number">23</span> Case Study</a></div>
<div class="next"><a href="LRINF.html"><span class="header-section-number">25</span> Linear Regression Inference</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#LRBASICS"><span class="header-section-number">24</span> Linear Regression Basics</a></li>
<li><a class="nav-link" href="#objectives-22"><span class="header-section-number">24.1</span> Objectives</a></li>
<li>
<a class="nav-link" href="#homework-23"><span class="header-section-number">24.2</span> Homework</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#problem-1-23"><span class="header-section-number">24.2.1</span> Problem 1</a></li></ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Solutions for Probability and Statistics for Scientists and Engineers</strong>" was written by Matthew Davis, Brianna Hitt, Kenneth Horton, Bradley Warner. It was last built on 2022-01-03.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
