<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 27 Simulation Based Linear Regression | Solutions for Probability and Statistics for Scientists and Engineers</title>
<meta name="author" content="Matthew Davis">
<meta name="author" content="Brianna Hitt">
<meta name="author" content="Kenneth Horton">
<meta name="author" content="Bradley Warner">
<meta name="description" content="27.1 Objectives Using the bootstrap, generate confidence and estimates of standard error for parameter estimates from a linear regression model. Generate and interpret bootstrap confidence...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 27 Simulation Based Linear Regression | Solutions for Probability and Statistics for Scientists and Engineers">
<meta property="og:type" content="book">
<meta property="og:image" content="/figures/SolutionCoverPSSE.png">
<meta property="og:description" content="27.1 Objectives Using the bootstrap, generate confidence and estimates of standard error for parameter estimates from a linear regression model. Generate and interpret bootstrap confidence...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 27 Simulation Based Linear Regression | Solutions for Probability and Statistics for Scientists and Engineers">
<meta name="twitter:description" content="27.1 Objectives Using the bootstrap, generate confidence and estimates of standard error for parameter estimates from a linear regression model. Generate and interpret bootstrap confidence...">
<meta name="twitter:image" content="/figures/SolutionCoverPSSE.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Solutions for Probability and Statistics for Scientists and Engineers</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li class="book-part">Descriptive Statistical Modeling</li>
<li><a class="" href="CS1.html"><span class="header-section-number">1</span> Case Study</a></li>
<li><a class="" href="DB.html"><span class="header-section-number">2</span> Data Basics</a></li>
<li><a class="" href="ODCP.html"><span class="header-section-number">3</span> Overview of Data Collection Principles</a></li>
<li><a class="" href="STUDY.html"><span class="header-section-number">4</span> Studies</a></li>
<li><a class="" href="NUMDATA.html"><span class="header-section-number">5</span> Numerical Data</a></li>
<li><a class="" href="CATDATA.html"><span class="header-section-number">6</span> Categorical Data</a></li>
<li class="book-part">Probability Modeling</li>
<li><a class="" href="CS2.html"><span class="header-section-number">7</span> Case Study</a></li>
<li><a class="" href="PROBRULES.html"><span class="header-section-number">8</span> Probability Rules</a></li>
<li><a class="" href="CONDPROB.html"><span class="header-section-number">9</span> Conditional Probability</a></li>
<li><a class="" href="RANDVAR.html"><span class="header-section-number">10</span> Random Variables</a></li>
<li><a class="" href="CONRANDVAR.html"><span class="header-section-number">11</span> Continuous Random Variables</a></li>
<li><a class="" href="DISCRETENAMED.html"><span class="header-section-number">12</span> Named Discrete Distributions</a></li>
<li><a class="" href="CONTNNAMED.html"><span class="header-section-number">13</span> Named Continuous Distributions</a></li>
<li><a class="" href="MULTIDISTS.html"><span class="header-section-number">14</span> Multivariate Distributions</a></li>
<li><a class="" href="EST.html"><span class="header-section-number">15</span> Estimation Methods</a></li>
<li class="book-part">Statistical Modeling</li>
<li><a class="" href="CS3.html"><span class="header-section-number">16</span> Case Study</a></li>
<li><a class="" href="HYPOTEST.html"><span class="header-section-number">17</span> Hypothesis Testing</a></li>
<li><a class="" href="PVALUES.html"><span class="header-section-number">18</span> Empirical p-values</a></li>
<li><a class="" href="CLT.html"><span class="header-section-number">19</span> Central Limit Theorem</a></li>
<li><a class="" href="CI.html"><span class="header-section-number">20</span> Confidence Intervals</a></li>
<li><a class="" href="BOOT.html"><span class="header-section-number">21</span> Bootstrap</a></li>
<li><a class="" href="ADDTESTS.html"><span class="header-section-number">22</span> Additional Hypothesis Tests</a></li>
<li class="book-part">Predictive Statistical Modeling</li>
<li><a class="" href="CS4.html"><span class="header-section-number">23</span> Case Study</a></li>
<li><a class="" href="LRBASICS.html"><span class="header-section-number">24</span> Linear Regression Basics</a></li>
<li><a class="" href="LRINF.html"><span class="header-section-number">25</span> Linear Regression Inference</a></li>
<li><a class="" href="LRDIAG.html"><span class="header-section-number">26</span> Regression Diagnostics</a></li>
<li><a class="active" href="LRSIM.html"><span class="header-section-number">27</span> Simulation Based Linear Regression</a></li>
<li><a class="" href="LRMULTI.html"><span class="header-section-number">28</span> Multiple Linear Regression</a></li>
<li><a class="" href="LOGREG.html"><span class="header-section-number">29</span> Logistic Regression</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="LRSIM" class="section level1" number="27">
<h1>
<span class="header-section-number">27</span> Simulation Based Linear Regression<a class="anchor" aria-label="anchor" href="#LRSIM"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-25" class="section level2" number="27.1">
<h2>
<span class="header-section-number">27.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-25"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: decimal">
<li>Using the bootstrap, generate confidence and estimates of standard error for parameter estimates from a linear regression model.<br>
</li>
<li>Generate and interpret bootstrap confidence intervals for predicted values.<br>
</li>
<li>Generate bootstrap samples from sampling rows of the data or sampling residuals. Explain why you might prefer one over the other.<br>
</li>
<li>Interpret regression coefficients for a linear model with a categorical explanatory variable.</li>
</ol>
</div>
<div id="homework-26" class="section level2" number="27.2">
<h2>
<span class="header-section-number">27.2</span> Homework<a class="anchor" aria-label="anchor" href="#homework-26"><i class="fas fa-link"></i></a>
</h2>
<p>We will use the loans data set again to create linear models. Remember this data set represents thousands of loans made through the Lending Club platform, which is a platform that allows individuals to lend to other individuals.</p>
<div id="problem-1-26" class="section level3" number="27.2.1">
<h3>
<span class="header-section-number">27.2.1</span> Problem 1<a class="anchor" aria-label="anchor" href="#problem-1-26"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Loans</strong></p>
<p>In this exercise we will examine the relationship between interest rate and loan amount.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data from <code>loans.csv</code> in the <code>data</code> folder.</li>
</ol>
<div class="sourceCode" id="cb622"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">loans</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/loans.csv"</span><span class="op">)</span></code></pre></div>
<ol start="2" style="list-style-type: lower-alpha">
<li>Create a subset of data with 200 with the following three variables <code>interest_rate</code>, <code>loan_amount</code>, and <code>term</code>. Change <code>term</code> into a factor and use a stratified sample to keep the proportion of loan term roughly the same as the original data.</li>
</ol>
<div class="sourceCode" id="cb623"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaicCore/man/tally.html">tally</a></span><span class="op">(</span><span class="op">~</span><span class="va">term</span>,data<span class="op">=</span><span class="va">loans</span>,format<span class="op">=</span><span class="st">"percent"</span><span class="op">)</span></code></pre></div>
<pre><code>## term
##   36   60 
## 69.7 30.3</code></pre>
<div class="sourceCode" id="cb625"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2111</span><span class="op">)</span>
<span class="va">loans200</span> <span class="op">&lt;-</span> <span class="va">loans</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">interest_rate</span>,<span class="va">loan_amount</span>,<span class="va">term</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>term<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">term</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">term</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_sample</a></span><span class="op">(</span>prop<span class="op">=</span><span class="fl">0.02</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb626"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaicCore/man/tally.html">tally</a></span><span class="op">(</span><span class="op">~</span><span class="va">term</span>,data<span class="op">=</span><span class="va">loans200</span>,format<span class="op">=</span><span class="st">"percent"</span><span class="op">)</span></code></pre></div>
<pre><code>## term
##       36       60 
## 69.84925 30.15075</code></pre>
<div class="sourceCode" id="cb628"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">loans200</span><span class="op">)</span></code></pre></div>
<pre><code>## tibble [199 × 3] (S3: tbl_df/tbl/data.frame)
##  $ interest_rate: num [1:199] 13.59 9.92 17.47 10.9 7.34 ...
##  $ loan_amount  : num [1:199] 13000 10000 10000 8400 4800 10000 6000 6300 10000 32000 ...
##  $ term         : Factor w/ 2 levels "36","60": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Plot <code>interest_rate</code> versus <code>loan_amount</code>. We think <code>interest_rate</code> should be the response.</li>
</ol>
<p>It seems natural that you would want to predict interest rate from loan amount.</p>
<div class="sourceCode" id="cb630"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">loans200</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">loan_amount</span>,y<span class="op">=</span><span class="va">interest_rate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title<span class="op">=</span><span class="st">"Lending Club"</span>,subtitle<span class="op">=</span><span class="st">"Loan amount versus Interest rate"</span>,
       x<span class="op">=</span><span class="st">"Loan Amount"</span>,y<span class="op">=</span><span class="st">"Interest rate (percent)"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-6-1.png" width="672"></div>
<ol start="4" style="list-style-type: lower-alpha">
<li>Fit a linear model to the data by regressing <code>interest_rate</code> on <code>loan_amount</code>. Is there a significant relationship between <code>interest_rate</code> and <code>loan_amount</code>?</li>
</ol>
<div class="sourceCode" id="cb631"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">int_rate_mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">interest_rate</span><span class="op">~</span><span class="va">loan_amount</span>,data<span class="op">=</span><span class="va">loans200</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb632"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">int_rate_mod</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = interest_rate ~ loan_amount, data = loans200)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.1611 -4.6842 -0.9666  3.0685 18.6280 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.165e+01  7.337e-01  15.874   &lt;2e-16 ***
## loan_amount 2.748e-05  3.722e-05   0.738    0.461    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.423 on 197 degrees of freedom
## Multiple R-squared:  0.002759,   Adjusted R-squared:  -0.002303 
## F-statistic: 0.545 on 1 and 197 DF,  p-value: 0.4613</code></pre>
<p>To test if there a significant relationship between <code>interest_rate</code> and <code>loan_amount</code>, we test if <span class="math inline">\(\beta_1 = 0\)</span>. The p-value for this is 0.4613, so we fail to reject that there is no relationship between <code>interest_rate</code> and <code>loan_amount</code>.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Using the <span class="math inline">\(t\)</span> distribution:
<ol style="list-style-type: lower-roman">
<li>Find a 95% confidence interval for the slope.<br>
</li>
<li>Find and interpret a 90% confidence interval for a loan amount of $20000.</li>
</ol>
</li>
</ol>
<div class="sourceCode" id="cb634"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/confint.html">confint</a></span><span class="op">(</span><span class="va">int_rate_mod</span><span class="op">)</span></code></pre></div>
<pre><code>##                     2.5 %       97.5 %
## (Intercept)  1.019986e+01 1.309374e+01
## loan_amount -4.592357e-05 1.008748e-04</code></pre>
<p>We are 95% confident the true slope is between -4.592357e-05 and 1.008748e-04.</p>
<div class="sourceCode" id="cb636"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">int_rate_mod</span>,newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>loan_amount<span class="op">=</span><span class="fl">20000</span><span class="op">)</span>,
        interval <span class="op">=</span> <span class="st">"confidence"</span>,level<span class="op">=</span><span class="fl">0.90</span><span class="op">)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 12.19631 11.53105 12.86157</code></pre>
<p>We are 90% confident that the average interest rate for a loan of $20000 is between 11.5% and 12.9%.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Repeat part e using a bootstrap.</li>
</ol>
<div class="sourceCode" id="cb638"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">3011</span><span class="op">)</span>
<span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">1000</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">interest_rate</span> <span class="op">~</span> <span class="va">loan_amount</span>,data<span class="op">=</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/resample.html">resample</a></span><span class="op">(</span><span class="va">loans200</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb639"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">results</span><span class="op">)</span></code></pre></div>
<pre><code>##   Intercept   loan_amount    sigma    r.squared          F numdf dendf .row
## 1  10.26651  6.837311e-05 4.893962 0.0184148594 3.69578466     1   197    1
## 2  11.63858  2.341492e-05 5.147715 0.0021348812 0.42147139     1   197    1
## 3  12.52116  6.096805e-06 5.138114 0.0001537970 0.03030266     1   197    1
## 4  11.93790 -6.489195e-06 5.284324 0.0001655171 0.03261227     1   197    1
## 5  11.38254  9.000912e-05 5.472851 0.0281911082 5.71475355     1   197    1
## 6  12.35924 -2.568690e-05 5.520788 0.0025489432 0.50342501     1   197    1
##   .index
## 1      1
## 2      2
## 3      3
## 4      4
## 5      5
## 6      6</code></pre>
<div class="sourceCode" id="cb641"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/pqrdata.html">cdata</a></span><span class="op">(</span><span class="op">~</span><span class="va">loan_amount</span>,data<span class="op">=</span><span class="va">results</span><span class="op">)</span></code></pre></div>
<pre><code>##              lower        upper central.p
## 2.5% -4.277717e-05 9.863203e-05      0.95</code></pre>
<p>Or using the <code>infer</code> package:</p>
<div class="sourceCode" id="cb643"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">results2</span> <span class="op">&lt;-</span> <span class="va">loans200</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">specify</span><span class="op">(</span><span class="va">interest_rate</span><span class="op">~</span><span class="va">loan_amount</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">generate</span><span class="op">(</span>reps<span class="op">=</span><span class="fl">1000</span>,type<span class="op">=</span><span class="st">"bootstrap"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">calculate</span><span class="op">(</span>stat<span class="op">=</span><span class="st">"slope"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">results2</span><span class="op">)</span></code></pre></div>
<pre><code>## Response: interest_rate (numeric)
## Explanatory: loan_amount (numeric)
## # A tibble: 6 × 2
##   replicate        stat
##       &lt;int&gt;       &lt;dbl&gt;
## 1         1 -0.0000114 
## 2         2  0.0000198 
## 3         3  0.0000207 
## 4         4  0.00000481
## 5         5  0.0000549 
## 6         6  0.0000531</code></pre>
<div class="sourceCode" id="cb645"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">get_confidence_interval</span><span class="op">(</span><span class="va">results2</span><span class="op">)</span></code></pre></div>
<pre><code>## Using `level = 0.95` to compute confidence interval.</code></pre>
<pre><code>## # A tibble: 1 × 2
##     lower_ci  upper_ci
##        &lt;dbl&gt;     &lt;dbl&gt;
## 1 -0.0000361 0.0000947</code></pre>
<p>Now the confidence interval for average interest rate at a loan amount of 20000:</p>
<div class="sourceCode" id="cb648"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">results</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pred<span class="op">=</span><span class="va">Intercept</span><span class="op">+</span><span class="va">loan_amount</span><span class="op">*</span><span class="fl">20000</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/pqrdata.html">cdata</a></span><span class="op">(</span><span class="op">~</span><span class="va">pred</span>,data<span class="op">=</span><span class="va">.</span><span class="op">)</span></code></pre></div>
<pre><code>##        lower    upper central.p
## 2.5% 11.4061 13.01508      0.95</code></pre>
<p>Again, close to what we had but slightly different. Maybe some of the assumptions such as normality are not appropriate.</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Check the assumptions of linear regression.</li>
</ol>
<div class="sourceCode" id="cb650"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">int_rate_mod</span><span class="op">)</span></code></pre></div>
<p><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-16-1.png" width="672"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-16-2.png" width="672"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-16-3.png" width="672"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-16-4.png" width="672"></p>
<p>There appears to be a lack of normality as the residuals are skewed to the right, large positive residuals. The bootstrap would probably be more appropriate for this problem.</p>
</div>
<div id="problem-2-24" class="section level3" number="27.2.2">
<h3>
<span class="header-section-number">27.2.2</span> Problem 2<a class="anchor" aria-label="anchor" href="#problem-2-24"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Loans II</strong></p>
<p>Using the <code>loans</code> data set of 200 observations from the previous exercise, use the variable <code>term</code> to determine if there is a difference in interest rates for the two different loan lengths.</p>
<ol style="list-style-type: lower-alpha">
<li>Build a set of side-by-side boxplots that summarize interest rate by term. Describe the relationship you see. Note: You will have to convert the <code>term</code> variable to a factor prior to continuing.</li>
</ol>
<div class="sourceCode" id="cb651"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">loans200</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_boxplot</span><span class="op">(</span><span class="va">interest_rate</span><span class="op">~</span><span class="va">term</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_theme</span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_labs</span><span class="op">(</span>title<span class="op">=</span><span class="st">"Lending Club"</span>,x<span class="op">=</span><span class="st">"Length of Loan"</span>,y<span class="op">=</span><span class="st">"Interest Rate"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-17-1.png" width="672"></div>
<p>It looks like there is a difference in interest rate based on the length of the loan. It also appears both are skewed to the right, positive skew. Let’s plot the density and see what we find.</p>
<div class="sourceCode" id="cb652"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">loans200</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_dens</span><span class="op">(</span><span class="op">~</span><span class="va">interest_rate</span>,group<span class="op">=</span><span class="op">~</span><span class="va">term</span>,color<span class="op">=</span><span class="op">~</span><span class="va">term</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_theme</span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu">gf_labs</span><span class="op">(</span>title<span class="op">=</span><span class="st">"Lending Club"</span>,x<span class="op">=</span><span class="st">"Interest Rate"</span>,y<span class="op">=</span><span class="st">"Density"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-18-1.png" width="672"></div>
<p>Just as we thought.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Build a linear model fitting interest rate against term. Does there appear to be a significant difference in mean interest rates by term?</li>
</ol>
<div class="sourceCode" id="cb653"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">int_rate_mod2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">interest_rate</span><span class="op">~</span><span class="va">term</span>,data<span class="op">=</span><span class="va">loans200</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb654"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">int_rate_mod2</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = interest_rate ~ term, data = loans200)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.643 -3.993 -1.263  3.132 15.597 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  10.7031     0.4230  25.304  &lt; 2e-16 ***
## term60        4.6601     0.7703   6.049 7.19e-09 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.987 on 197 degrees of freedom
## Multiple R-squared:  0.1567, Adjusted R-squared:  0.1524 
## F-statistic:  36.6 on 1 and 197 DF,  p-value: 7.189e-09</code></pre>
<p>There is a significant difference between the average interest rate based on the length of the loan.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Write out the estimated linear model. In words, interpret the coefficient estimate.</li>
</ol>
<p>The intercept <span class="math inline">\(\beta_\text{Intercept} = \mu_\text{term36}\)</span> is the average interest rate for a 36 month loan. And <span class="math inline">\(\beta_\text{term60} = \mu_\text{term60} - \mu_\text{term36}\)</span> is the difference in average interest rates between loan length. In this case, a 60 month loan is 4.66 percentage points higher on average than a 36 month loan.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Construct a bootstrap confidence interval on the coefficient.</li>
</ol>
<div class="sourceCode" id="cb656"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">331</span><span class="op">)</span>
<span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/do.html">do</a></span><span class="op">(</span><span class="fl">1000</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">interest_rate</span> <span class="op">~</span> <span class="va">term</span>,data<span class="op">=</span><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/resample.html">resample</a></span><span class="op">(</span><span class="va">loans200</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">results</span><span class="op">)</span></code></pre></div>
<pre><code>##   Intercept   term60    sigma  r.squared        F numdf dendf .row .index
## 1  10.11890 4.903166 4.534598 0.20352136 50.33871     1   197    1      1
## 2  10.91695 5.275981 5.220399 0.17564679 41.97523     1   197    1      2
## 3  11.07592 4.064085 5.226607 0.11097921 24.59212     1   197    1      3
## 4  11.14948 3.675445 5.250290 0.09818999 21.44956     1   197    1      4
## 5  10.45978 4.941671 4.960234 0.17698753 42.36454     1   197    1      5
## 6  11.02597 4.232862 4.891180 0.13743012 31.38729     1   197    1      6</code></pre>
<div class="sourceCode" id="cb658"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/pqrdata.html">cdata</a></span><span class="op">(</span><span class="op">~</span><span class="va">term60</span>,data<span class="op">=</span><span class="va">results</span><span class="op">)</span></code></pre></div>
<pre><code>##         lower    upper central.p
## 2.5% 3.029483 6.242261      0.95</code></pre>
<p>We are 95% confident the difference in average interest rates for loans of 60 month and 36 month is between 3.03% and 6.24%.</p>
<p>Let’s check using the assumption of normally distributed errors.</p>
<div class="sourceCode" id="cb660"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/confint.html">confint</a></span><span class="op">(</span><span class="va">int_rate_mod2</span><span class="op">)</span></code></pre></div>
<pre><code>##                2.5 %    97.5 %
## (Intercept) 9.868936 11.537251
## term60      3.140928  6.179218</code></pre>
<p>Close, but slightly narrower.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Check model assumptions.</li>
</ol>
<div class="sourceCode" id="cb662"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">int_rate_mod2</span><span class="op">)</span></code></pre></div>
<p><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-24-1.png" width="672"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-24-2.png" width="672"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-24-3.png" width="672"><img src="29-Simulation-Based-Linear-Regression-Solutions_files/figure-html/unnamed-chunk-24-4.png" width="672"></p>
<p>Because of the discrete nature of the predictor, only the first two plots are of interest. The assumption of constant variable does seem reasonable but the assumption of normally distributed errors is not. We have a positive skewness.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="LRDIAG.html"><span class="header-section-number">26</span> Regression Diagnostics</a></div>
<div class="next"><a href="LRMULTI.html"><span class="header-section-number">28</span> Multiple Linear Regression</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#LRSIM"><span class="header-section-number">27</span> Simulation Based Linear Regression</a></li>
<li><a class="nav-link" href="#objectives-25"><span class="header-section-number">27.1</span> Objectives</a></li>
<li>
<a class="nav-link" href="#homework-26"><span class="header-section-number">27.2</span> Homework</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#problem-1-26"><span class="header-section-number">27.2.1</span> Problem 1</a></li>
<li><a class="nav-link" href="#problem-2-24"><span class="header-section-number">27.2.2</span> Problem 2</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Solutions for Probability and Statistics for Scientists and Engineers</strong>" was written by Matthew Davis, Brianna Hitt, Kenneth Horton, Bradley Warner. It was last built on 2022-01-03.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
